-- 2) Status Indicator Tables (8)

-- 2.1 base template
CREATE TABLE ACCOUNT_STATUS_IND (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL UNIQUE,
  label VARCHAR(255) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;

-- 2.3 IND table with same structure
CREATE TABLE GYM_STATUS_IND LIKE ACCOUNT_STATUS_IND;
CREATE TABLE EQUIPMENT_STATUS_IND LIKE ACCOUNT_STATUS_IND;
CREATE TABLE SESSION_STATUS_IND LIKE ACCOUNT_STATUS_IND;
CREATE TABLE AVAILABILITY_STATUS_IND LIKE ACCOUNT_STATUS_IND;
CREATE TABLE PLAN_STATUS_IND LIKE ACCOUNT_STATUS_IND;
CREATE TABLE ACCESS_CARD_STATUS_IND LIKE ACCOUNT_STATUS_IND;
CREATE TABLE BOOKING_STATUS_IND LIKE ACCOUNT_STATUS_IND;

-- 2.4 status values inserted
INSERT IGNORE INTO ACCOUNT_STATUS_IND(code,label) VALUES
 ('ACTIVE','Active'),('INACTIVE','Inactive'),('LOCKED','Locked'),('SUSPENDED','Suspended'),('CANCELED','Canceled');
INSERT IGNORE INTO GYM_STATUS_IND(code,label) VALUES ('ACTIVE','Active'),('INACTIVE','Inactive');
INSERT IGNORE INTO EQUIPMENT_STATUS_IND(code,label) VALUES ('OK','Ok'),('NEEDS_SERVICE','Needs service'),('OUT_OF_ORDER','Out of order'),('RETIRED','Retired');
INSERT IGNORE INTO SESSION_STATUS_IND(code,label) VALUES ('SCHEDULED','Scheduled'),('CANCELED','Canceled'),('COMPLETED','Completed');
INSERT IGNORE INTO AVAILABILITY_STATUS_IND(code,label) VALUES ('AVAILABLE','Available'),('UNAVAILABLE','Unavailable');
INSERT IGNORE INTO PLAN_STATUS_IND(code,label) VALUES ('ACTIVE','Active'),('RETIRED','Retired');
INSERT IGNORE INTO ACCESS_CARD_STATUS_IND(code,label) VALUES ('ACTIVE','Active'),('LOST','Lost'),('REVOKED','Revoked');
INSERT IGNORE INTO BOOKING_STATUS_IND(code,label) VALUES ('CONFIRMED','Confirmed'),('CANCELED_MEMBER','Canceled by member'),('CANCELED_SYSTEM','Canceled by system');