-- 4) Audit Tables (22) ----
-- made sure to not have before_json (append-only history lets us reconstruct to a point in time)
-- seq_no provides strict ordering in case timestamps collide/get messed up

---- 4.1 drop user audit table ----
DROP TABLE IF EXISTS USER_AUD;

---- 4.2 create user audit table ----
CREATE TABLE USER_AUD (
  seq_no BIGINT PRIMARY KEY AUTO_INCREMENT,
  base_entity_id BIGINT NOT NULL,
  occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  action ENUM('insert','update','delete') NOT NULL,
  after_json JSON NULL,
  actor_user_id BIGINT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY k_useraud_entity_seq (base_entity_id, seq_no),
  KEY k_useraud_actor_seq (actor_user_id, seq_no),
  CONSTRAINT fk_useraud_user FOREIGN KEY (base_entity_id) REFERENCES USER(id),
  CONSTRAINT fk_useraud_actor FOREIGN KEY (actor_user_id) REFERENCES USER(id)
) ENGINE=InnoDB;

---- 4.3 drop other audit tables ----
DROP TABLE IF EXISTS STAFF_AUD, TRAINER_AUD, MANAGER_AUD, FLOOR_MANAGER_AUD, FRONT_DESK_AUD, ADMIN_AUD, SUPER_ADMIN_AUD;

---- 4.4 create other audit tables ----
CREATE TABLE STAFF_AUD LIKE USER_AUD;            ALTER TABLE STAFF_AUD            DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_staffaud_staff FOREIGN KEY(base_entity_id) REFERENCES STAFF(id);
CREATE TABLE TRAINER_AUD LIKE USER_AUD;          ALTER TABLE TRAINER_AUD          DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_trainaud_tr FOREIGN KEY(base_entity_id) REFERENCES TRAINER(id);
CREATE TABLE MANAGER_AUD LIKE USER_AUD;          ALTER TABLE MANAGER_AUD          DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_manaud_mgr FOREIGN KEY(base_entity_id) REFERENCES MANAGER(id);
CREATE TABLE FLOOR_MANAGER_AUD LIKE USER_AUD;    ALTER TABLE FLOOR_MANAGER_AUD    DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_fmaud_fm FOREIGN KEY(base_entity_id) REFERENCES FLOOR_MANAGER(id);
CREATE TABLE FRONT_DESK_AUD LIKE USER_AUD;       ALTER TABLE FRONT_DESK_AUD       DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_fdaud_fd FOREIGN KEY(base_entity_id) REFERENCES FRONT_DESK(id);
CREATE TABLE ADMIN_AUD LIKE USER_AUD;            ALTER TABLE ADMIN_AUD            DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_adminaud_admin FOREIGN KEY(base_entity_id) REFERENCES ADMIN(id);
CREATE TABLE SUPER_ADMIN_AUD LIKE USER_AUD;      ALTER TABLE SUPER_ADMIN_AUD      DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_supaud_sa FOREIGN KEY(base_entity_id) REFERENCES SUPER_ADMIN(id);

---- 4.5 drop gym audit tables ----
DROP TABLE IF EXISTS GYM_AUD, EQUIP_KIND_AUD, EQUIPMENT_ITEM_AUD, INVENTORY_COUNT_AUD, SERVICE_LOG_AUD;

---- 4.6 create gym audit tables ----
CREATE TABLE GYM_AUD LIKE USER_AUD;              ALTER TABLE GYM_AUD              DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_gym_aud FOREIGN KEY(base_entity_id) REFERENCES GYM(id);
CREATE TABLE EQUIP_KIND_AUD LIKE USER_AUD;       ALTER TABLE EQUIP_KIND_AUD       DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_ekind_aud FOREIGN KEY(base_entity_id) REFERENCES EQUIP_KIND(id);
CREATE TABLE EQUIPMENT_ITEM_AUD LIKE USER_AUD;   ALTER TABLE EQUIPMENT_ITEM_AUD   DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_eitem_aud FOREIGN KEY(base_entity_id) REFERENCES EQUIPMENT_ITEM(id);
CREATE TABLE INVENTORY_COUNT_AUD LIKE USER_AUD;  ALTER TABLE INVENTORY_COUNT_AUD  DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_invc_aud FOREIGN KEY(base_entity_id) REFERENCES INVENTORY_COUNT(id);
CREATE TABLE SERVICE_LOG_AUD LIKE USER_AUD;      ALTER TABLE SERVICE_LOG_AUD      DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_slog_aud FOREIGN KEY(base_entity_id) REFERENCES SERVICE_LOG(id);

---- 4.7 drop class session audit tables ----
DROP TABLE IF EXISTS CLASS_SESSION_AUD, TRAINER_AVAIL_DATE_AUD, SESSION_TRAINER_AUD, SESSION_EQUIP_RES_AUD;

---- 4.8 create class session audit tables ----
CREATE TABLE CLASS_SESSION_AUD LIKE USER_AUD;        ALTER TABLE CLASS_SESSION_AUD        DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_csaud_cs FOREIGN KEY(base_entity_id) REFERENCES CLASS_SESSION(id);
CREATE TABLE TRAINER_AVAIL_DATE_AUD LIKE USER_AUD;   ALTER TABLE TRAINER_AVAIL_DATE_AUD   DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_tavaud_ta FOREIGN KEY(base_entity_id) REFERENCES TRAINER_AVAIL_DATE(id);
CREATE TABLE SESSION_TRAINER_AUD LIKE USER_AUD;      ALTER TABLE SESSION_TRAINER_AUD      DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_stra_aud FOREIGN KEY(base_entity_id) REFERENCES SESSION_TRAINER(id);
CREATE TABLE SESSION_EQUIP_RES_AUD LIKE USER_AUD;    ALTER TABLE SESSION_EQUIP_RES_AUD    DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_sereq_aud FOREIGN KEY(base_entity_id) REFERENCES SESSION_EQUIP_RESERVATION(id);

---- 4.9 drop membership plan audit tables ----
DROP TABLE IF EXISTS MEMBERSHIP_PLAN_AUD, MEMBER_AUD, BOOKING_AUD, CHECK_IN_AUD, ACCESS_CARD_AUD;

---- 4.10 create membership plan audit tables ----
CREATE TABLE MEMBERSHIP_PLAN_AUD LIKE USER_AUD;  ALTER TABLE MEMBERSHIP_PLAN_AUD  DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_mplaud_mp FOREIGN KEY(base_entity_id) REFERENCES MEMBERSHIP_PLAN(id);
CREATE TABLE MEMBER_AUD LIKE USER_AUD;           ALTER TABLE MEMBER_AUD           DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_memaud_member FOREIGN KEY(base_entity_id) REFERENCES MEMBER(id);
CREATE TABLE BOOKING_AUD LIKE USER_AUD;          ALTER TABLE BOOKING_AUD          DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_bookaud_booking FOREIGN KEY(base_entity_id) REFERENCES BOOKING(id);
CREATE TABLE CHECK_IN_AUD LIKE USER_AUD;         ALTER TABLE CHECK_IN_AUD         DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_ckinaud_checkin FOREIGN KEY(base_entity_id) REFERENCES CHECK_IN(id);
CREATE TABLE ACCESS_CARD_AUD LIKE USER_AUD;      ALTER TABLE ACCESS_CARD_AUD      DROP FOREIGN KEY fk_useraud_user, ADD CONSTRAINT fk_acardaud_card FOREIGN KEY(base_entity_id) REFERENCES ACCESS_CARD(id);