-- Bulk Copy Script for FitDB
-- Loads CSV files generated by generate_seed.py into the database
-- Run this after build.sql has created the schema

-- Use the fitdb database
USE `fitdb`;

-- Enable local_infile for this session (requires SUPER or SYSTEM_VARIABLES_ADMIN privilege)
SET GLOBAL local_infile = 1;

-- Temporarily disable constraints, checks, and triggers for faster loading
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
SET AUTOCOMMIT = 0;
SET @DISABLE_AUTO_TRIGGERS = 1;  -- Disable auto-create triggers during bulk load

-- Set the path to CSV files
-- NOTE: MySQL's LOAD DATA LOCAL INFILE requires the path to be relative to where mysql is executed
-- When using the Makefile, mysql is run from the project root, so paths are relative to that
-- Alternatively, use absolute paths if needed

-- 1. Load GYM data
LOAD DATA LOCAL INFILE 'data/csvs/gym.csv'
INTO TABLE GYM
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, name, address, status_id, created_at, updated_at);

-- 2. Load MEMBERSHIP_PLAN data
LOAD DATA LOCAL INFILE 'data/csvs/membership_plan.csv'
INTO TABLE MEMBERSHIP_PLAN
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, name, tier, billing_cycle, price, status_id, created_at, updated_at);

-- 3. Load EQUIP_KIND data
LOAD DATA LOCAL INFILE 'data/csvs/equip_kind.csv'
INTO TABLE EQUIP_KIND
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, name, mode, created_at, updated_at);

-- 4. Load USER data (includes both members and staff)
LOAD DATA LOCAL INFILE 'data/csvs/user.csv'
INTO TABLE USER
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, username, email, password_hash, password_algo, @password_updated_at, @last_login_at, 
 @profile_photo_path, status_id, created_at, updated_at)
SET 
  password_updated_at = NULLIF(@password_updated_at, ''),
  last_login_at = NULLIF(@last_login_at, ''),
  profile_photo_path = NULLIF(@profile_photo_path, '');

-- 5. Load STAFF data
LOAD DATA LOCAL INFILE 'data/csvs/staff.csv'
INTO TABLE STAFF
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, user_id, gym_id, status_id, @notes, created_at, updated_at)
SET notes = NULLIF(@notes, '');

-- 6. Load MEMBER data
LOAD DATA LOCAL INFILE 'data/csvs/member.csv'
INTO TABLE MEMBER
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, user_id, membership_plan_id, @home_gym_id, joined_on, @trial_expires_on, 
 status_id, created_at, updated_at)
SET 
  home_gym_id = NULLIF(@home_gym_id, ''),
  trial_expires_on = NULLIF(@trial_expires_on, '');

-- 7. Load TRAINER data
LOAD DATA LOCAL INFILE 'data/csvs/trainer.csv'
INTO TABLE TRAINER
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, staff_id, @certification, @bio, created_at, updated_at)
SET 
  certification = NULLIF(@certification, ''),
  bio = NULLIF(@bio, '');

-- 8. Load MANAGER data
LOAD DATA LOCAL INFILE 'data/csvs/manager.csv'
INTO TABLE MANAGER
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, staff_id, scope, created_at, updated_at);

-- 9. Load FLOOR_MANAGER data
LOAD DATA LOCAL INFILE 'data/csvs/floor_manager.csv'
INTO TABLE FLOOR_MANAGER
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, staff_id, scope, created_at, updated_at);

-- 10. Load FRONT_DESK data
LOAD DATA LOCAL INFILE 'data/csvs/front_desk.csv'
INTO TABLE FRONT_DESK
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, staff_id, capabilities, created_at, updated_at);

-- 11. Load ADMIN data
LOAD DATA LOCAL INFILE 'data/csvs/admin.csv'
INTO TABLE ADMIN
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, staff_id, scope, created_at, updated_at);

-- 12. Load SUPER_ADMIN data
LOAD DATA LOCAL INFILE 'data/csvs/super_admin.csv'
INTO TABLE SUPER_ADMIN
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, user_id, scope, created_at, updated_at);

-- 13. Load EQUIPMENT_ITEM data
LOAD DATA LOCAL INFILE 'data/csvs/equipment_item.csv'
INTO TABLE EQUIPMENT_ITEM
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, gym_id, equip_kind_id, status_id, @serial_no, uses_count, rated_uses, 
 @last_serviced_at, last_cleaned_at, cleaning_interval_uses, cleaning_interval_days,
 next_clean_due_at, service_required, cleaning_required, created_at, updated_at)
SET 
  serial_no = NULLIF(@serial_no, ''),
  last_serviced_at = NULLIF(@last_serviced_at, '');

-- 14. Load INVENTORY_COUNT data
LOAD DATA LOCAL INFILE 'data/csvs/inventory_count.csv'
INTO TABLE INVENTORY_COUNT
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, gym_id, equip_kind_id, qty_on_floor, qty_in_storage, reorder_needed,
 @updated_snapshot_at, created_at, updated_at)
SET updated_snapshot_at = NULLIF(@updated_snapshot_at, '');

-- 15. Load SERVICE_LOG data
LOAD DATA LOCAL INFILE 'data/csvs/service_log.csv'
INTO TABLE SERVICE_LOG
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, equipment_item_id, serviced_at, action, @notes, @staff_id, created_at, updated_at)
SET 
  notes = NULLIF(@notes, ''),
  staff_id = NULLIF(@staff_id, '');

-- 16. Load CLASS_SESSION data
LOAD DATA LOCAL INFILE 'data/csvs/class_session.csv'
INTO TABLE CLASS_SESSION
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, gym_id, title, @description, starts_at, ends_at, capacity, max_trainers,
 open_for_booking, status_id, created_at, updated_at)
SET description = NULLIF(@description, '');

-- 17. Load TRAINER_AVAIL_DATE data
LOAD DATA LOCAL INFILE 'data/csvs/trainer_avail_date.csv'
INTO TABLE TRAINER_AVAIL_DATE
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, trainer_id, gym_id, for_date, period, status_id, created_at, updated_at);

-- 18. Load SESSION_TRAINER data
LOAD DATA LOCAL INFILE 'data/csvs/session_trainer.csv'
INTO TABLE SESSION_TRAINER
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, session_id, trainer_id, role, assigned_at, created_at, updated_at);

-- 19. Load SESSION_EQUIP_RESERVATION data
LOAD DATA LOCAL INFILE 'data/csvs/session_equip_reservation.csv'
INTO TABLE SESSION_EQUIP_RESERVATION
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, session_id, equip_kind_id, quantity, created_at, updated_at);

-- 20. Load BOOKING data
LOAD DATA LOCAL INFILE 'data/csvs/booking.csv'
INTO TABLE BOOKING
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, session_id, member_id, status_id, booked_at, @cancellation_reason, @notes,
 created_at, updated_at)
SET 
  cancellation_reason = NULLIF(@cancellation_reason, ''),
  notes = NULLIF(@notes, '');

-- 21. Load ACCESS_CARD data
LOAD DATA LOCAL INFILE 'data/csvs/access_card.csv'
INTO TABLE ACCESS_CARD
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, member_id, gym_id, card_uid, status_id, issued_at, @revoked_at, created_at, updated_at)
SET revoked_at = NULLIF(@revoked_at, '');

-- 22. Load CHECK_IN data
LOAD DATA LOCAL INFILE 'data/csvs/check_in.csv'
INTO TABLE CHECK_IN
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(id, member_id, gym_id, @access_card_id, checked_in_at, method, created_at, updated_at)
SET access_card_id = NULLIF(@access_card_id, '');

-- Commit all changes
COMMIT;

-- Re-enable constraints, checks, and triggers
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
SET AUTOCOMMIT = 1;
SET @DISABLE_AUTO_TRIGGERS = 0;

-- Display summary of loaded data
SELECT 'Data loading complete!' AS Status;

SELECT 'GYM' AS TableName, COUNT(*) AS RowCount FROM GYM
UNION ALL SELECT 'USER', COUNT(*) FROM USER
UNION ALL SELECT 'MEMBER', COUNT(*) FROM MEMBER
UNION ALL SELECT 'STAFF', COUNT(*) FROM STAFF
UNION ALL SELECT 'TRAINER', COUNT(*) FROM TRAINER
UNION ALL SELECT 'MANAGER', COUNT(*) FROM MANAGER
UNION ALL SELECT 'FLOOR_MANAGER', COUNT(*) FROM FLOOR_MANAGER
UNION ALL SELECT 'FRONT_DESK', COUNT(*) FROM FRONT_DESK
UNION ALL SELECT 'ADMIN', COUNT(*) FROM ADMIN
UNION ALL SELECT 'SUPER_ADMIN', COUNT(*) FROM SUPER_ADMIN
UNION ALL SELECT 'EQUIP_KIND', COUNT(*) FROM EQUIP_KIND
UNION ALL SELECT 'EQUIPMENT_ITEM', COUNT(*) FROM EQUIPMENT_ITEM
UNION ALL SELECT 'INVENTORY_COUNT', COUNT(*) FROM INVENTORY_COUNT
UNION ALL SELECT 'SERVICE_LOG', COUNT(*) FROM SERVICE_LOG
UNION ALL SELECT 'CLASS_SESSION', COUNT(*) FROM CLASS_SESSION
UNION ALL SELECT 'TRAINER_AVAIL_DATE', COUNT(*) FROM TRAINER_AVAIL_DATE
UNION ALL SELECT 'SESSION_TRAINER', COUNT(*) FROM SESSION_TRAINER
UNION ALL SELECT 'SESSION_EQUIP_RESERVATION', COUNT(*) FROM SESSION_EQUIP_RESERVATION
UNION ALL SELECT 'MEMBERSHIP_PLAN', COUNT(*) FROM MEMBERSHIP_PLAN
UNION ALL SELECT 'BOOKING', COUNT(*) FROM BOOKING
UNION ALL SELECT 'ACCESS_CARD', COUNT(*) FROM ACCESS_CARD
UNION ALL SELECT 'CHECK_IN', COUNT(*) FROM CHECK_IN
ORDER BY TableName;

